# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 22:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_auto_20170826_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='school',
        ),
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
