# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_auto_20170919_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.Assignment'),
            preserve_default=False,
        ),
    ]
