# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170316_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sms_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
