# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170316_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='enrolling_students',
            field=models.BooleanField(default=False),
        ),
    ]
