# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_classroom_enrolling_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
