# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:35
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=dashboard.models.Classroom)),
                ('attendance', jsonfield.fields.JSONField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Classroom')),
            ],
        ),
    ]
