# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:39
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name=dashboard.models.Classroom),
        ),
    ]
