# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170321_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='enrolling_students',
        ),
        migrations.AddField(
            model_name='teacher',
            name='active_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='active_model_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
