# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20170328_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='active_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Classroom'),
        ),
    ]
