# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20170401_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
