# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'present'), ('tardy', 'tardy'), ('absent', 'absent')], default='absent', max_length=7)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Classroom')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Student'),
        ),
    ]
